import '../components/navigation/navigation.js';
import '../components/gallery/gallery.js';
import '../components/slider/slider.js';
import '../components/watch-info/watch-info.js';
import '../components/range/range.js';
import '../components/filter/filter.js';
import '../components/select/select.js';
import '../components/watch-card/watch-card.js';
import '../components/product-list/product-list.js';